jdbcUrl=${DB_URL}
username=${DB_USER}
password=${DB_PASS}
driverClassName = com.mysql.cj.jdbc.Driver
maximumPoolSize = 5
minimumIdle = 1
idleTimeout = 300000
connectionTimeout = 30000
maxLifetime = 18000000
poolName = HikariCP
autoCommit = true
transactionIsolation = TRANSACTION_READ_COMMITTED
connectionTestQuery = SELECT 1
initializationFailTimeout = 0
